name: dev work
on: [push]

jobs: 
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some text
        run: echo "Some Text"
      - name: command in multitul
        run: |
          node -v
          npm -v  