name: 2dev work
on: [push]

jobs: 
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display node version
        run: node -v
            
  run-paralel-comad:
    run-on: widows-latest
    step:
      - name: Display Node version
        run: node -v
  